apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-creds
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    creationPolicy: "Owner"
    name: argocd-creds
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
  dataFrom:
    - extract:
        key: infra/shared/argocd