apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://git-codecommit.eu-central-1.amazonaws.com/v1/repos/management-cluster
    targetRevision: HEAD
    path: ./manifests/argo-events
   
  destination:
    server: https://kubernetes.default.svc
    namespace: argo

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: 
      prune: true
      selfHeal: true