apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://git-codecommit.eu-central-1.amazonaws.com/v1/repos/management-cluster
    targetRevision: HEAD
    path: ./manifests/aws-load-balancer-controller
   
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated: 
      prune: true
      selfHeal: true