apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: IRSA
  assumeRoleChain:
    - roleARN: "arn:aws:iam::<AWS_ACCOUNT_ID>:role/ORG_CROSSPLANE_ACCESS"
