apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-events
subjects:
  - kind: ServiceAccount
    name: operate-workflow-sa
    namespace: argo