apiVersion: v2
name: argo-events
description: A helm chart to deploy argo-events
type: application
version: 1.0.0
dependencies:
- name: argo-events
  version: 2.4.1
  repository: https://argoproj.github.io/argo-helm
